/** Symbol/slug → CoinGecko coin id (top ~100 by market cap) */
export const COIN_MAP: Record<string, string> = {
  btc: "bitcoin",
  bitcoin: "bitcoin",
  eth: "ethereum",
  ethereum: "ethereum",
  usdt: "tether",
  tether: "tether",
  bnb: "binancecoin",
  binancecoin: "binancecoin",
  sol: "solana",
  solana: "solana",
  xrp: "ripple",
  ripple: "ripple",
  usdc: "usd-coin",
  "usd-coin": "usd-coin",
  ada: "cardano",
  cardano: "cardano",
  avax: "avalanche-2",
  avalanche: "avalanche-2",
  doge: "dogecoin",
  dogecoin: "dogecoin",
  dot: "polkadot",
  polkadot: "polkadot",
  trx: "tron",
  tron: "tron",
  link: "chainlink",
  chainlink: "chainlink",
  matic: "matic-network",
  polygon: "matic-network",
  "matic-network": "matic-network",
  shib: "shiba-inu",
  "shiba-inu": "shiba-inu",
  ltc: "litecoin",
  litecoin: "litecoin",
  bch: "bitcoin-cash",
  "bitcoin-cash": "bitcoin-cash",
  uni: "uniswap",
  uniswap: "uniswap",
  atom: "cosmos",
  cosmos: "cosmos",
  xlm: "stellar",
  stellar: "stellar",
  xmr: "monero",
  monero: "monero",
  etc: "ethereum-classic",
  "ethereum-classic": "ethereum-classic",
  fil: "filecoin",
  filecoin: "filecoin",
  apt: "aptos",
  aptos: "aptos",
  arb: "arbitrum",
  arbitrum: "arbitrum",
  op: "optimism",
  optimism: "optimism",
  near: "near",
  vet: "vechain",
  vechain: "vechain",
  icp: "internet-computer",
  hbar: "hedera-hashgraph",
  algo: "algorand",
  algorand: "algorand",
  qnt: "quant-network",
  eos: "eos",
  aave: "aave",
  grt: "the-graph",
  sand: "the-sandbox",
  mana: "decentraland",
  axs: "axie-infinity",
  theta: "theta-token",
  ftm: "fantom",
  fantom: "fantom",
  xtz: "tezos",
  tezos: "tezos",
  rune: "thorchain",
  snx: "havven",
  crv: "curve-dao-token",
  mkr: "maker",
  maker: "maker",
  comp: "compound-governance-token",
  ldo: "lido-dao",
  sui: "sui",
  sei: "sei-network",
  inj: "injective-protocol",
  tia: "celestia",
  pepe: "pepe",
  wif: "dogwifcoin",
  bonk: "bonk",
  floki: "floki",
  render: "render-token",
  rndr: "render-token",
  fet: "fetch-ai",
  imx: "immutable-x",
  gala: "gala",
  enj: "enjincoin",
  bat: "basic-attention-token",
  zec: "zcash",
  dash: "dash",
  neo: "neo",
  kcs: "kucoin-shares",
  okb: "okb",
  ton: "the-open-network",
  kas: "kaspa",
  stx: "blockstack",
  rpl: "rocket-pool",
  blur: "blur",
  pendle: "pendle",
  jup: "jupiter-exchange-solana",
  pyth: "pyth-network",
  wld: "worldcoin-wld",
  strk: "starknet",
  ethfi: "ether-fi",
  ena: "ethena",
  ondo: "ondo-finance",
  not: "notcoin",
  bome: "book-of-meme",
  ar: "arweave",
  flow: "flow",
  mina: "mina-protocol",
  ro: "ronin",
  ronin: "ronin",
  egld: "elrond-erd-2",
  egld_m: "elrond-erd-2",
  cake: "pancakeswap-token",
  "1inch": "1inch",
  ens: "ethereum-name-service",
  chz: "chiliz",
  hot: "holotoken",
  zil: "zilliqa",
  icx: "icon",
  waves: "waves",
  kava: "kava",
  celo: "celo",
  rose: "oasis-network",
  one: "harmony",
  iota: "iota",
  xem: "nem",
  sc: "siacoin",
  dcr: "decred",
  rvn: "ravencoin",
  zen: "zencash",
  ont: "ontology",
  qtum: "qtum",
  btt: "bittorrent",
  hnt: "helium",
  lrc: "loopring",
  ankr: "ankr",
  omg: "omisego",
  storj: "storj",
  skl: "skale",
  celr: "celer-network",
  coti: "coti",
  ren: "republic-protocol",
  band: "band-protocol",
  ocean: "ocean-protocol",
  api3: "api3",
  nmr: "numeraire",
  bal: "balancer",
  yfi: "yearn-finance",
  sushi: "sushi",
  dydx: "dydx-chain",
  gmx: "gmx",
  magic: "magic",
  rdnt: "radiant-capital",
  joe: "joe",
  woo: "woo-network",
  perp: "perpetual-protocol",
  lqty: "liquity",
  cvx: "convex-finance",
  frax: "frax",
  fxn: "fxn",
  usdd: "usdd",
  tusd: "true-usd",
  dai: "dai",
  frax_usd: "frax",
};

export const FIAT_CURRENCIES = [
  "usd",
  "eur",
  "gbp",
  "jpy",
  "aud",
  "cad",
  "chf",
  "cny",
  "inr",
  "pkr",
  "krw",
  "sgd",
  "hkd",
  "nzd",
  "brl",
  "mxn",
  "try",
  "rub",
  "zar",
  "aed",
  "sar",
  "ngn",
  "php",
  "idr",
  "thb",
  "vnd",
  "myr",
  "pln",
  "sek",
  "nok",
  "dkk",
  "czk",
  "huf",
  "ils",
  "twd",
  "clp",
  "cop",
  "ars",
  "pen",
  "uah",
  "bdt",
  "lkr",
  "kes",
  "ghs",
  "egp",
] as const;

export const GAS_CHAIN_IDS: Record<string, number> = {
  eth: 1,
  bnb: 56,
  polygon: 137,
  arbitrum: 42161,
  base: 8453,
};

export const GAS_SCAN_APIS: Partial<
  Record<string, { url: string; apiKeyEnv: string }>
> = {
  eth: { url: "https://api.etherscan.io/api", apiKeyEnv: "ETHERSCAN_API_KEY" },
  bnb: { url: "https://api.bscscan.com/api", apiKeyEnv: "BSCSCAN_API_KEY" },
  polygon: {
    url: "https://api.polygonscan.com/api",
    apiKeyEnv: "POLYGONSCAN_API_KEY",
  },
  arbitrum: {
    url: "https://api.arbiscan.io/api",
    apiKeyEnv: "ARBISCAN_API_KEY",
  },
  base: { url: "https://api.basescan.org/api", apiKeyEnv: "BASESCAN_API_KEY" },
};

export const USER_AGENT = "mcp-crypto-price/1.0.0 (https://github.com/mcp-crypto-price)";
